### PR TITLE
Added dual-screen and Wii Remote support

### PR DESCRIPTION
**Pull request by CreeperMario**
I made modifications to 'draw.c' and 'draw.h' that allow for rendering
to the TV and GamePad screens separately. I have also added
'padscore.h', which provides data structures that are compatible with
functions from 'padscore.rpl' on the Wii U.

### CODE REVIEW

**Comment by PistonMiner** [comment]
I believe rather than copying every function and flipping a zero to a one, an additional parameter would be a much better solution.

**Comment by CreeperMario** [comment]
While that is a good idea, shortening it into one function AND providing backwards compatibility with older versions of libwiiu is really hard in C99. From my research (I am still relatively new to C), GCC 4.9 has simplified support for default variables in functions, but the latest revision of devkitPPC is unfortunately based on GCC 4.8.2.

If you really feel that backwards compatibility is not important, then I'll be happy to add an argument to the normal functions and remove the bloated functions.

@Relys until a coclusion is reached, please don't merge this.

**Comment by CreeperMario** [comment]
I've just committed some changes that neaten up the code-base and remove the bloat that I added. I thought that now we had an ELF loader that it wouldn't matter, but neater code is always better code. I also feel stupid for not exploring this method in the first place, but that's programming!

(For the following examples, I will use `drawString(int x, int y, char * string)`.)

I have replaced all the functions in the drawing library (`drawString(int x, int y, char * string)`) with new fangled EX functions (`drawString(bool tv, bool pad, int x, int y, char * string)`). These functions, as you can see, contain true/false values that decide whether to draw to the TV, GamePad or to both screens.

I have also provided simple wrapper functions for backwards compatibility with software build using older versions of libwiiu. Calling `drawString(0, 0, "Hello World!");` is perfectly equivalent to calling `drawStringEx(true, true, 0, 0, "Hello World!");` However, if you prefer to call the EX functions directly, you may do so, just remove the non-EX functions as they are unneeded bloat.

If there are no more complaints with with my code (;P) then feel free to merge it into libwiiu.

**Comment by phase** [comment]
My complaints:
1. I think the method names with the flags shouldn't have `Ex` in them. `drawString, drawStringTV, drawStringPad` should be fine. Backwards compatibility is something that I don't think is needed. A library will evolve over time, and people using that library will have to adapt to using it.
2. You only need one flag, as if that flag is false the other one is obviously true (I believe that you only have the TV and the pad to go between). That's why `else` was invented.
3. The flags should be at the end, as that's usually where flags go in functions arguments.

**Comment by PistonMiner** [comment]
Well, I think it's supposed to be able to write both in one call. This could be solved practically and future-proofable with a flag field.

**Comment by phase** [comment]
Ah, that makes sense.

**Pull request closed without merging**
